/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clark_glfw3_GLFW */

#ifndef _Included_com_clark_glfw3_GLFW
#define _Included_com_clark_glfw3_GLFW
#ifdef __cplusplus
extern "C" {
#endif
#undef com_clark_glfw3_GLFW_GLFW_NOT_INITIALIZED
#define com_clark_glfw3_GLFW_GLFW_NOT_INITIALIZED 65537L
#undef com_clark_glfw3_GLFW_GLFW_NO_CURRENT_CONTEXT
#define com_clark_glfw3_GLFW_GLFW_NO_CURRENT_CONTEXT 65538L
#undef com_clark_glfw3_GLFW_GLFW_INVALID_ENUM
#define com_clark_glfw3_GLFW_GLFW_INVALID_ENUM 65539L
#undef com_clark_glfw3_GLFW_GLFW_INVALID_VALUE
#define com_clark_glfw3_GLFW_GLFW_INVALID_VALUE 65540L
#undef com_clark_glfw3_GLFW_GLFW_OUT_OF_MEMORY
#define com_clark_glfw3_GLFW_GLFW_OUT_OF_MEMORY 65541L
#undef com_clark_glfw3_GLFW_GLFW_API_UNAVAILABLE
#define com_clark_glfw3_GLFW_GLFW_API_UNAVAILABLE 65542L
#undef com_clark_glfw3_GLFW_GLFW_VERSION_UNAVAILABLE
#define com_clark_glfw3_GLFW_GLFW_VERSION_UNAVAILABLE 65543L
#undef com_clark_glfw3_GLFW_GLFW_PLATFORM_ERROR
#define com_clark_glfw3_GLFW_GLFW_PLATFORM_ERROR 65544L
#undef com_clark_glfw3_GLFW_GLFW_FORMAT_UNAVAILABLE
#define com_clark_glfw3_GLFW_GLFW_FORMAT_UNAVAILABLE 65545L
#undef com_clark_glfw3_GLFW_GLFW_RELEASE
#define com_clark_glfw3_GLFW_GLFW_RELEASE 0L
#undef com_clark_glfw3_GLFW_GLFW_PRESS
#define com_clark_glfw3_GLFW_GLFW_PRESS 1L
#undef com_clark_glfw3_GLFW_GLFW_REPEAT
#define com_clark_glfw3_GLFW_GLFW_REPEAT 2L
/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_GLFW_Init
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    Terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_Terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetVersion
 * Signature: ()Lcom/clark/glfw3/Version;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_GLFW_GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clark_glfw3_GLFW_GetVersionString
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    MakeContextCurrent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_MakeContextCurrent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_clark_glfw3_GLFW_GetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    SwapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_SwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    IsExtensionSupported
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_GLFW_IsExtensionSupported
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetProcFuncAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_clark_glfw3_GLFW_GetProcFuncAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_clark_glfw3_GLFW_GetTime
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    SetTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_SetTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    SetErrorCallback
 * Signature: (Lcom/clark/glfw3/GLFW$ErrorCallback;)Lcom/clark/glfw3/GLFW$ErrorCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_GLFW_SetErrorCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
