/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clark_glfw3_Window */

#ifndef _Included_com_clark_glfw3_Window
#define _Included_com_clark_glfw3_Window
#ifdef __cplusplus
extern "C" {
#endif
#undef com_clark_glfw3_Window_GLFW_NOT_INITIALIZED
#define com_clark_glfw3_Window_GLFW_NOT_INITIALIZED 65537L
#undef com_clark_glfw3_Window_GLFW_NO_CURRENT_CONTEXT
#define com_clark_glfw3_Window_GLFW_NO_CURRENT_CONTEXT 65538L
#undef com_clark_glfw3_Window_GLFW_INVALID_ENUM
#define com_clark_glfw3_Window_GLFW_INVALID_ENUM 65539L
#undef com_clark_glfw3_Window_GLFW_INVALID_VALUE
#define com_clark_glfw3_Window_GLFW_INVALID_VALUE 65540L
#undef com_clark_glfw3_Window_GLFW_OUT_OF_MEMORY
#define com_clark_glfw3_Window_GLFW_OUT_OF_MEMORY 65541L
#undef com_clark_glfw3_Window_GLFW_API_UNAVAILABLE
#define com_clark_glfw3_Window_GLFW_API_UNAVAILABLE 65542L
#undef com_clark_glfw3_Window_GLFW_VERSION_UNAVAILABLE
#define com_clark_glfw3_Window_GLFW_VERSION_UNAVAILABLE 65543L
#undef com_clark_glfw3_Window_GLFW_PLATFORM_ERROR
#define com_clark_glfw3_Window_GLFW_PLATFORM_ERROR 65544L
#undef com_clark_glfw3_Window_GLFW_FORMAT_UNAVAILABLE
#define com_clark_glfw3_Window_GLFW_FORMAT_UNAVAILABLE 65545L
#undef com_clark_glfw3_Window_GLFW_RELEASE
#define com_clark_glfw3_Window_GLFW_RELEASE 0L
#undef com_clark_glfw3_Window_GLFW_PRESS
#define com_clark_glfw3_Window_GLFW_PRESS 1L
#undef com_clark_glfw3_Window_GLFW_REPEAT
#define com_clark_glfw3_Window_GLFW_REPEAT 2L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_1
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_1 0L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_2
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_2 1L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_3
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_3 2L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_4
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_4 3L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_5
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_5 4L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_6
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_6 5L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_7
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_7 6L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_8
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_8 7L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_LAST
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_LAST 7L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_LEFT
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_LEFT 0L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_RIGHT
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_RIGHT 1L
#undef com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_MIDDLE
#define com_clark_glfw3_Window_GLFW_MOUSE_BUTTON_MIDDLE 2L
#undef com_clark_glfw3_Window_GLFW_MOD_SHIFT
#define com_clark_glfw3_Window_GLFW_MOD_SHIFT 1L
#undef com_clark_glfw3_Window_GLFW_MOD_CONTROL
#define com_clark_glfw3_Window_GLFW_MOD_CONTROL 2L
#undef com_clark_glfw3_Window_GLFW_MOD_ALT
#define com_clark_glfw3_Window_GLFW_MOD_ALT 4L
#undef com_clark_glfw3_Window_GLFW_MOD_SUPER
#define com_clark_glfw3_Window_GLFW_MOD_SUPER 8L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_1
#define com_clark_glfw3_Window_GLFW_JOYSTICK_1 0L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_2
#define com_clark_glfw3_Window_GLFW_JOYSTICK_2 1L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_3
#define com_clark_glfw3_Window_GLFW_JOYSTICK_3 2L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_4
#define com_clark_glfw3_Window_GLFW_JOYSTICK_4 3L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_5
#define com_clark_glfw3_Window_GLFW_JOYSTICK_5 4L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_6
#define com_clark_glfw3_Window_GLFW_JOYSTICK_6 5L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_7
#define com_clark_glfw3_Window_GLFW_JOYSTICK_7 6L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_8
#define com_clark_glfw3_Window_GLFW_JOYSTICK_8 7L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_9
#define com_clark_glfw3_Window_GLFW_JOYSTICK_9 8L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_10
#define com_clark_glfw3_Window_GLFW_JOYSTICK_10 9L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_11
#define com_clark_glfw3_Window_GLFW_JOYSTICK_11 10L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_12
#define com_clark_glfw3_Window_GLFW_JOYSTICK_12 11L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_13
#define com_clark_glfw3_Window_GLFW_JOYSTICK_13 12L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_14
#define com_clark_glfw3_Window_GLFW_JOYSTICK_14 13L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_15
#define com_clark_glfw3_Window_GLFW_JOYSTICK_15 14L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_16
#define com_clark_glfw3_Window_GLFW_JOYSTICK_16 15L
#undef com_clark_glfw3_Window_GLFW_JOYSTICK_LAST
#define com_clark_glfw3_Window_GLFW_JOYSTICK_LAST 15L
#undef com_clark_glfw3_Window_GLFW_KEY_UNKNOWN
#define com_clark_glfw3_Window_GLFW_KEY_UNKNOWN -1L
#undef com_clark_glfw3_Window_GLFW_KEY_SPACE
#define com_clark_glfw3_Window_GLFW_KEY_SPACE 32L
#undef com_clark_glfw3_Window_GLFW_KEY_APOSTROPHE
#define com_clark_glfw3_Window_GLFW_KEY_APOSTROPHE 39L
#undef com_clark_glfw3_Window_GLFW_KEY_COMMA
#define com_clark_glfw3_Window_GLFW_KEY_COMMA 44L
#undef com_clark_glfw3_Window_GLFW_KEY_MINUS
#define com_clark_glfw3_Window_GLFW_KEY_MINUS 45L
#undef com_clark_glfw3_Window_GLFW_KEY_PERIOD
#define com_clark_glfw3_Window_GLFW_KEY_PERIOD 46L
#undef com_clark_glfw3_Window_GLFW_KEY_SLASH
#define com_clark_glfw3_Window_GLFW_KEY_SLASH 47L
#undef com_clark_glfw3_Window_GLFW_KEY_0
#define com_clark_glfw3_Window_GLFW_KEY_0 48L
#undef com_clark_glfw3_Window_GLFW_KEY_1
#define com_clark_glfw3_Window_GLFW_KEY_1 49L
#undef com_clark_glfw3_Window_GLFW_KEY_2
#define com_clark_glfw3_Window_GLFW_KEY_2 50L
#undef com_clark_glfw3_Window_GLFW_KEY_3
#define com_clark_glfw3_Window_GLFW_KEY_3 51L
#undef com_clark_glfw3_Window_GLFW_KEY_4
#define com_clark_glfw3_Window_GLFW_KEY_4 52L
#undef com_clark_glfw3_Window_GLFW_KEY_5
#define com_clark_glfw3_Window_GLFW_KEY_5 53L
#undef com_clark_glfw3_Window_GLFW_KEY_6
#define com_clark_glfw3_Window_GLFW_KEY_6 54L
#undef com_clark_glfw3_Window_GLFW_KEY_7
#define com_clark_glfw3_Window_GLFW_KEY_7 55L
#undef com_clark_glfw3_Window_GLFW_KEY_8
#define com_clark_glfw3_Window_GLFW_KEY_8 56L
#undef com_clark_glfw3_Window_GLFW_KEY_9
#define com_clark_glfw3_Window_GLFW_KEY_9 57L
#undef com_clark_glfw3_Window_GLFW_KEY_SEMICOLON
#define com_clark_glfw3_Window_GLFW_KEY_SEMICOLON 59L
#undef com_clark_glfw3_Window_GLFW_KEY_EQUAL
#define com_clark_glfw3_Window_GLFW_KEY_EQUAL 61L
#undef com_clark_glfw3_Window_GLFW_KEY_A
#define com_clark_glfw3_Window_GLFW_KEY_A 65L
#undef com_clark_glfw3_Window_GLFW_KEY_B
#define com_clark_glfw3_Window_GLFW_KEY_B 66L
#undef com_clark_glfw3_Window_GLFW_KEY_C
#define com_clark_glfw3_Window_GLFW_KEY_C 67L
#undef com_clark_glfw3_Window_GLFW_KEY_D
#define com_clark_glfw3_Window_GLFW_KEY_D 68L
#undef com_clark_glfw3_Window_GLFW_KEY_E
#define com_clark_glfw3_Window_GLFW_KEY_E 69L
#undef com_clark_glfw3_Window_GLFW_KEY_F
#define com_clark_glfw3_Window_GLFW_KEY_F 70L
#undef com_clark_glfw3_Window_GLFW_KEY_G
#define com_clark_glfw3_Window_GLFW_KEY_G 71L
#undef com_clark_glfw3_Window_GLFW_KEY_H
#define com_clark_glfw3_Window_GLFW_KEY_H 72L
#undef com_clark_glfw3_Window_GLFW_KEY_I
#define com_clark_glfw3_Window_GLFW_KEY_I 73L
#undef com_clark_glfw3_Window_GLFW_KEY_J
#define com_clark_glfw3_Window_GLFW_KEY_J 74L
#undef com_clark_glfw3_Window_GLFW_KEY_K
#define com_clark_glfw3_Window_GLFW_KEY_K 75L
#undef com_clark_glfw3_Window_GLFW_KEY_L
#define com_clark_glfw3_Window_GLFW_KEY_L 76L
#undef com_clark_glfw3_Window_GLFW_KEY_M
#define com_clark_glfw3_Window_GLFW_KEY_M 77L
#undef com_clark_glfw3_Window_GLFW_KEY_N
#define com_clark_glfw3_Window_GLFW_KEY_N 78L
#undef com_clark_glfw3_Window_GLFW_KEY_O
#define com_clark_glfw3_Window_GLFW_KEY_O 79L
#undef com_clark_glfw3_Window_GLFW_KEY_P
#define com_clark_glfw3_Window_GLFW_KEY_P 80L
#undef com_clark_glfw3_Window_GLFW_KEY_Q
#define com_clark_glfw3_Window_GLFW_KEY_Q 81L
#undef com_clark_glfw3_Window_GLFW_KEY_R
#define com_clark_glfw3_Window_GLFW_KEY_R 82L
#undef com_clark_glfw3_Window_GLFW_KEY_S
#define com_clark_glfw3_Window_GLFW_KEY_S 83L
#undef com_clark_glfw3_Window_GLFW_KEY_T
#define com_clark_glfw3_Window_GLFW_KEY_T 84L
#undef com_clark_glfw3_Window_GLFW_KEY_U
#define com_clark_glfw3_Window_GLFW_KEY_U 85L
#undef com_clark_glfw3_Window_GLFW_KEY_V
#define com_clark_glfw3_Window_GLFW_KEY_V 86L
#undef com_clark_glfw3_Window_GLFW_KEY_W
#define com_clark_glfw3_Window_GLFW_KEY_W 87L
#undef com_clark_glfw3_Window_GLFW_KEY_X
#define com_clark_glfw3_Window_GLFW_KEY_X 88L
#undef com_clark_glfw3_Window_GLFW_KEY_Y
#define com_clark_glfw3_Window_GLFW_KEY_Y 89L
#undef com_clark_glfw3_Window_GLFW_KEY_Z
#define com_clark_glfw3_Window_GLFW_KEY_Z 90L
#undef com_clark_glfw3_Window_GLFW_KEY_LEFT_BRACKET
#define com_clark_glfw3_Window_GLFW_KEY_LEFT_BRACKET 91L
#undef com_clark_glfw3_Window_GLFW_KEY_BACKSLASH
#define com_clark_glfw3_Window_GLFW_KEY_BACKSLASH 92L
#undef com_clark_glfw3_Window_GLFW_KEY_RIGHT_BRACKET
#define com_clark_glfw3_Window_GLFW_KEY_RIGHT_BRACKET 93L
#undef com_clark_glfw3_Window_GLFW_KEY_GRAVE_ACCENT
#define com_clark_glfw3_Window_GLFW_KEY_GRAVE_ACCENT 96L
#undef com_clark_glfw3_Window_GLFW_KEY_WORLD_1
#define com_clark_glfw3_Window_GLFW_KEY_WORLD_1 161L
#undef com_clark_glfw3_Window_GLFW_KEY_WORLD_2
#define com_clark_glfw3_Window_GLFW_KEY_WORLD_2 162L
#undef com_clark_glfw3_Window_GLFW_KEY_ESCAPE
#define com_clark_glfw3_Window_GLFW_KEY_ESCAPE 256L
#undef com_clark_glfw3_Window_GLFW_KEY_ENTER
#define com_clark_glfw3_Window_GLFW_KEY_ENTER 257L
#undef com_clark_glfw3_Window_GLFW_KEY_TAB
#define com_clark_glfw3_Window_GLFW_KEY_TAB 258L
#undef com_clark_glfw3_Window_GLFW_KEY_BACKSPACE
#define com_clark_glfw3_Window_GLFW_KEY_BACKSPACE 259L
#undef com_clark_glfw3_Window_GLFW_KEY_INSERT
#define com_clark_glfw3_Window_GLFW_KEY_INSERT 260L
#undef com_clark_glfw3_Window_GLFW_KEY_DELETE
#define com_clark_glfw3_Window_GLFW_KEY_DELETE 261L
#undef com_clark_glfw3_Window_GLFW_KEY_RIGHT
#define com_clark_glfw3_Window_GLFW_KEY_RIGHT 262L
#undef com_clark_glfw3_Window_GLFW_KEY_LEFT
#define com_clark_glfw3_Window_GLFW_KEY_LEFT 263L
#undef com_clark_glfw3_Window_GLFW_KEY_DOWN
#define com_clark_glfw3_Window_GLFW_KEY_DOWN 264L
#undef com_clark_glfw3_Window_GLFW_KEY_UP
#define com_clark_glfw3_Window_GLFW_KEY_UP 265L
#undef com_clark_glfw3_Window_GLFW_KEY_PAGE_UP
#define com_clark_glfw3_Window_GLFW_KEY_PAGE_UP 266L
#undef com_clark_glfw3_Window_GLFW_KEY_PAGE_DOWN
#define com_clark_glfw3_Window_GLFW_KEY_PAGE_DOWN 267L
#undef com_clark_glfw3_Window_GLFW_KEY_HOME
#define com_clark_glfw3_Window_GLFW_KEY_HOME 268L
#undef com_clark_glfw3_Window_GLFW_KEY_END
#define com_clark_glfw3_Window_GLFW_KEY_END 269L
#undef com_clark_glfw3_Window_GLFW_KEY_CAPS_LOCK
#define com_clark_glfw3_Window_GLFW_KEY_CAPS_LOCK 280L
#undef com_clark_glfw3_Window_GLFW_KEY_SCROLL_LOCK
#define com_clark_glfw3_Window_GLFW_KEY_SCROLL_LOCK 281L
#undef com_clark_glfw3_Window_GLFW_KEY_NUM_LOCK
#define com_clark_glfw3_Window_GLFW_KEY_NUM_LOCK 282L
#undef com_clark_glfw3_Window_GLFW_KEY_PRINT_SCREEN
#define com_clark_glfw3_Window_GLFW_KEY_PRINT_SCREEN 283L
#undef com_clark_glfw3_Window_GLFW_KEY_PAUSE
#define com_clark_glfw3_Window_GLFW_KEY_PAUSE 284L
#undef com_clark_glfw3_Window_GLFW_KEY_F1
#define com_clark_glfw3_Window_GLFW_KEY_F1 290L
#undef com_clark_glfw3_Window_GLFW_KEY_F2
#define com_clark_glfw3_Window_GLFW_KEY_F2 291L
#undef com_clark_glfw3_Window_GLFW_KEY_F3
#define com_clark_glfw3_Window_GLFW_KEY_F3 292L
#undef com_clark_glfw3_Window_GLFW_KEY_F4
#define com_clark_glfw3_Window_GLFW_KEY_F4 293L
#undef com_clark_glfw3_Window_GLFW_KEY_F5
#define com_clark_glfw3_Window_GLFW_KEY_F5 294L
#undef com_clark_glfw3_Window_GLFW_KEY_F6
#define com_clark_glfw3_Window_GLFW_KEY_F6 295L
#undef com_clark_glfw3_Window_GLFW_KEY_F7
#define com_clark_glfw3_Window_GLFW_KEY_F7 296L
#undef com_clark_glfw3_Window_GLFW_KEY_F8
#define com_clark_glfw3_Window_GLFW_KEY_F8 297L
#undef com_clark_glfw3_Window_GLFW_KEY_F9
#define com_clark_glfw3_Window_GLFW_KEY_F9 298L
#undef com_clark_glfw3_Window_GLFW_KEY_F10
#define com_clark_glfw3_Window_GLFW_KEY_F10 299L
#undef com_clark_glfw3_Window_GLFW_KEY_F11
#define com_clark_glfw3_Window_GLFW_KEY_F11 300L
#undef com_clark_glfw3_Window_GLFW_KEY_F12
#define com_clark_glfw3_Window_GLFW_KEY_F12 301L
#undef com_clark_glfw3_Window_GLFW_KEY_F13
#define com_clark_glfw3_Window_GLFW_KEY_F13 302L
#undef com_clark_glfw3_Window_GLFW_KEY_F14
#define com_clark_glfw3_Window_GLFW_KEY_F14 303L
#undef com_clark_glfw3_Window_GLFW_KEY_F15
#define com_clark_glfw3_Window_GLFW_KEY_F15 304L
#undef com_clark_glfw3_Window_GLFW_KEY_F16
#define com_clark_glfw3_Window_GLFW_KEY_F16 305L
#undef com_clark_glfw3_Window_GLFW_KEY_F17
#define com_clark_glfw3_Window_GLFW_KEY_F17 306L
#undef com_clark_glfw3_Window_GLFW_KEY_F18
#define com_clark_glfw3_Window_GLFW_KEY_F18 307L
#undef com_clark_glfw3_Window_GLFW_KEY_F19
#define com_clark_glfw3_Window_GLFW_KEY_F19 308L
#undef com_clark_glfw3_Window_GLFW_KEY_F20
#define com_clark_glfw3_Window_GLFW_KEY_F20 309L
#undef com_clark_glfw3_Window_GLFW_KEY_F21
#define com_clark_glfw3_Window_GLFW_KEY_F21 310L
#undef com_clark_glfw3_Window_GLFW_KEY_F22
#define com_clark_glfw3_Window_GLFW_KEY_F22 311L
#undef com_clark_glfw3_Window_GLFW_KEY_F23
#define com_clark_glfw3_Window_GLFW_KEY_F23 312L
#undef com_clark_glfw3_Window_GLFW_KEY_F24
#define com_clark_glfw3_Window_GLFW_KEY_F24 313L
#undef com_clark_glfw3_Window_GLFW_KEY_F25
#define com_clark_glfw3_Window_GLFW_KEY_F25 314L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_0
#define com_clark_glfw3_Window_GLFW_KEY_KP_0 320L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_1
#define com_clark_glfw3_Window_GLFW_KEY_KP_1 321L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_2
#define com_clark_glfw3_Window_GLFW_KEY_KP_2 322L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_3
#define com_clark_glfw3_Window_GLFW_KEY_KP_3 323L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_4
#define com_clark_glfw3_Window_GLFW_KEY_KP_4 324L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_5
#define com_clark_glfw3_Window_GLFW_KEY_KP_5 325L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_6
#define com_clark_glfw3_Window_GLFW_KEY_KP_6 326L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_7
#define com_clark_glfw3_Window_GLFW_KEY_KP_7 327L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_8
#define com_clark_glfw3_Window_GLFW_KEY_KP_8 328L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_9
#define com_clark_glfw3_Window_GLFW_KEY_KP_9 329L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_DECIMAL
#define com_clark_glfw3_Window_GLFW_KEY_KP_DECIMAL 330L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_DIVIDE
#define com_clark_glfw3_Window_GLFW_KEY_KP_DIVIDE 331L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_MULTIPLY
#define com_clark_glfw3_Window_GLFW_KEY_KP_MULTIPLY 332L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_SUBTRACT
#define com_clark_glfw3_Window_GLFW_KEY_KP_SUBTRACT 333L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_ADD
#define com_clark_glfw3_Window_GLFW_KEY_KP_ADD 334L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_ENTER
#define com_clark_glfw3_Window_GLFW_KEY_KP_ENTER 335L
#undef com_clark_glfw3_Window_GLFW_KEY_KP_EQUAL
#define com_clark_glfw3_Window_GLFW_KEY_KP_EQUAL 336L
#undef com_clark_glfw3_Window_GLFW_KEY_LEFT_SHIFT
#define com_clark_glfw3_Window_GLFW_KEY_LEFT_SHIFT 340L
#undef com_clark_glfw3_Window_GLFW_KEY_LEFT_CONTROL
#define com_clark_glfw3_Window_GLFW_KEY_LEFT_CONTROL 341L
#undef com_clark_glfw3_Window_GLFW_KEY_LEFT_ALT
#define com_clark_glfw3_Window_GLFW_KEY_LEFT_ALT 342L
#undef com_clark_glfw3_Window_GLFW_KEY_LEFT_SUPER
#define com_clark_glfw3_Window_GLFW_KEY_LEFT_SUPER 343L
#undef com_clark_glfw3_Window_GLFW_KEY_RIGHT_SHIFT
#define com_clark_glfw3_Window_GLFW_KEY_RIGHT_SHIFT 344L
#undef com_clark_glfw3_Window_GLFW_KEY_RIGHT_CONTROL
#define com_clark_glfw3_Window_GLFW_KEY_RIGHT_CONTROL 345L
#undef com_clark_glfw3_Window_GLFW_KEY_RIGHT_ALT
#define com_clark_glfw3_Window_GLFW_KEY_RIGHT_ALT 346L
#undef com_clark_glfw3_Window_GLFW_KEY_RIGHT_SUPER
#define com_clark_glfw3_Window_GLFW_KEY_RIGHT_SUPER 347L
#undef com_clark_glfw3_Window_GLFW_KEY_MENU
#define com_clark_glfw3_Window_GLFW_KEY_MENU 348L
#undef com_clark_glfw3_Window_GLFW_KEY_LAST
#define com_clark_glfw3_Window_GLFW_KEY_LAST 348L
/*
 * Class:     com_clark_glfw3_Window
 * Method:    ResetHintsToDefault
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_ResetHintsToDefault
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetHint
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetHint
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Create
 * Signature: (IILjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_clark_glfw3_Window_Create
  (JNIEnv *, jclass, jint, jint, jstring, jlong, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetCloseFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_GetCloseFlag
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetCloseFlag
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_SetCloseFlag
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetPosition
 * Signature: (J)Lcom/clark/glfw3/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_GetPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetPosition
 * Signature: (JLcom/clark/glfw3/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetPosition
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetSize
 * Signature: (J)Lcom/clark/glfw3/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_GetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetSize
 * Signature: (JLcom/clark/glfw3/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetSize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetFramebufferSize
 * Signature: (J)Lcom/clark/glfw3/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_GetFramebufferSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Iconify
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_Iconify
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Restore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_Restore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Show
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_Show
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Hide
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_Hide
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetMonitor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_clark_glfw3_Window_GetMonitor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetAttribute
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_GetAttribute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetUserPointer
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetUserPointer
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetUserPointer
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_GetUserPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SwapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SwapBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    PollEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_PollEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    WaitEvents
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_WaitEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetClipboardString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetClipboardString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetClipboardString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clark_glfw3_Window_GetClipboardString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetPositionCallback
 * Signature: (JLcom/clark/glfw3/Window$PositionCallback;)Lcom/clark/glfw3/Window$PositionCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetPositionCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetSizeCallback
 * Signature: (JLcom/clark/glfw3/Window$SizeCallback;)Lcom/clark/glfw3/Window$SizeCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetSizeCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetCloseCallback
 * Signature: (JLcom/clark/glfw3/Window$CloseCallback;)Lcom/clark/glfw3/Window$CloseCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetCloseCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetRefreshCallback
 * Signature: (JLcom/clark/glfw3/Window$RefreshCallback;)Lcom/clark/glfw3/Window$RefreshCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetRefreshCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetFocusCallback
 * Signature: (JLcom/clark/glfw3/Window$FocusCallback;)Lcom/clark/glfw3/Window$FocusCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetFocusCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetIconifyCallback
 * Signature: (JLcom/clark/glfw3/Window$IconifyCallback;)Lcom/clark/glfw3/Window$IconifyCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetIconifyCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetFrameBufferSizeCallback
 * Signature: (JLcom/clark/glfw3/Window$FrameBufferSizeCallback;)Lcom/clark/glfw3/Window$FrameBufferSizeCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetFrameBufferSizeCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetInputMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_GetInputMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetInputMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetInputMode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetKey
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_GetKey
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetMouseButton
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_GetMouseButton
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetCursorPosition
 * Signature: (J)Lcom/clark/glfw3/PositionF;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_GetCursorPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetCursorPosition
 * Signature: (JLcom/clark/glfw3/PositionF;)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_Window_SetCursorPosition
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    JoystickPresent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_Window_JoystickPresent
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetJoystickAxes
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_clark_glfw3_Window_GetJoystickAxes
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetJoystickButtons
 * Signature: (I)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_clark_glfw3_Window_GetJoystickButtons
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    GetJoystickName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clark_glfw3_Window_GetJoystickName
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetMouseButtonCallback
 * Signature: (JLcom/clark/glfw3/Window$MouseButtonCallback;)Lcom/clark/glfw3/Window$MouseButtonCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetMouseButtonCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetCursorPositionCallback
 * Signature: (JLcom/clark/glfw3/Window$CursorPositionCallback;)Lcom/clark/glfw3/Window$CursorPositionCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetCursorPositionCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetCursorEnterCallback
 * Signature: (JLcom/clark/glfw3/Window$CursorEnterCallback;)Lcom/clark/glfw3/Window$CursorEnterCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetCursorEnterCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetScrollCallback
 * Signature: (JLcom/clark/glfw3/Window$ScrollCallback;)Lcom/clark/glfw3/Window$ScrollCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetScrollCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetKeyCallback
 * Signature: (JLcom/clark/glfw3/Window$KeyCallback;)Lcom/clark/glfw3/Window$KeyCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetKeyCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_clark_glfw3_Window
 * Method:    SetCharCallback
 * Signature: (JLcom/clark/glfw3/Window$CharCallback;)Lcom/clark/glfw3/Window$CharCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_Window_SetCharCallback
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
