/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clark_glfw3_GLFW */

#ifndef _Included_com_clark_glfw3_GLFW
#define _Included_com_clark_glfw3_GLFW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_GLFW_Init
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    Terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_Terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetVersion
 * Signature: ()Lcom/clark/glfw3/Version;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_GLFW_GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clark_glfw3_GLFW_GetVersionString
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    MakeContextCurrent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_MakeContextCurrent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_clark_glfw3_GLFW_GetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    SwapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_SwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    IsExtensionSupported
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_clark_glfw3_GLFW_IsExtensionSupported
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetProcFuncAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_clark_glfw3_GLFW_GetProcFuncAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    GetTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_clark_glfw3_GLFW_GetTime
  (JNIEnv *, jclass);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    SetTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_clark_glfw3_GLFW_SetTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_clark_glfw3_GLFW
 * Method:    SetErrorCallback
 * Signature: (Lcom/clark/glfw3/GLFW$ErrorCallback;)Lcom/clark/glfw3/GLFW$ErrorCallback;
 */
JNIEXPORT jobject JNICALL Java_com_clark_glfw3_GLFW_SetErrorCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
